// AUTHENTICATION TYPES
export const AUTHENTICATED = 'AUTHENTICATED'
export const UNAUTHENTICATED = 'UNAUTHENTICATED'
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING = 'LOADING'
export const LOADED = 'LOADED'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const USER_LOGGED = 'USER_LOGGED'
export const CHANGE_PRIVACY = 'CHANGE_PRIVACY'
export const SET_PASSWORD_AS_TRUE = 'SET_PASSWORD_AS_TRUE'
export const SET_PASSWORD_AS_FALSE = 'SET_PASSWORD_AS_FALSE'
// DATA TYPES
export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const SET_SELECTED_PROFILE = 'SET_SELECTED_PROFILE'
export const SET_SELECTED_POSTS = 'SET_SELECTED_POSTS'
export const SET_NEW_POST = 'SET_NEW_POST'
export const DELETE_POST = 'DELETE_POST'
// USER TYPES
export const SET_SUBSCRIPTIONS_POSTS = 'SET_SUBSCRIPTIONS_POSTS'
export const CLEAN_POSTS = 'CLEAN_POSTS'
export const SET_USERS = 'SET_USERS'
export const SET_POST_COMMENTS = 'SET_POST_COMMENTS'
export const SET_POST = 'SET_POST'
export const SET_REPLYS = 'SET_REPLYS'
export const SET_LIKES = 'SET_LIKES'
export const SET_DISLIKE = 'SET_DISLIKE'
// UI TYPES
export const SET_LOADING = 'SET_LOADING'
export const SET_LOADED = 'SET_LOADED'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const ON_SINGLE_POST = 'ON_SINGLE_POST'
export const CLOSE_SINGLE_POST = 'CLOSE_SINGLE_POST'
export const UPLOADING = 'UPLOADING'
export const UPLOADED = 'UPLOADED'
export const DELETING = 'DELETING'
export const DELETED = 'DELETED'
export const LOADING_SUB = 'LOADING_SUB'
export const LOADED_SUB = 'LOADED_SUB'
export const SET_FOLLOWED_USER = 'SET_FOLLOWED_USER'
export const LOADING_PROFILE = 'LOADING_PROFILE'
export const PROFILE_LOADED = 'PROFILE LOADED'
// NOTIFICATION TYPES
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'


export const SET_NEW_SUBSCRIPTIONS_POSTS = 'SET_NEW_SUBSCRIPTIONS_POSTS'

export const CANCEL_REQUEST = 'CANCEL_REQUEST'




