// AUTHENTICATION TYPES
export const AUTHENTICATED = 'AUTHENTICATED'
export const UNAUTHENTICATED = 'UNAUTHENTICATED'
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING = 'LOADING'
export const LOADED = 'LOADED'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const USER_LOGGED = 'USER_LOGGED'
// USER TYPES
export const CHANGE_PRIVACY = 'CHANGE_PRIVACY'
export const SET_PASSWORD_AS_TRUE = 'SET_PASSWORD_AS_TRUE'
export const SET_PASSWORD_AS_FALSE = 'SET_PASSWORD_AS_FALSE'
export const SET_UPDATED_USERS = 'SET_UPDATED_USERS'
export const SET_NEW_IMAGE = 'SET_NEW_IMAGE'
export const CANCEL_REQUEST = 'CANCEL_REQUEST'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
export const ADD_TO_REQUESTS = 'ADD_TO_REQUESTS'
export const DELETE_REQUEST = 'DELETE_REQUEST'
export const ADD_REQUEST = 'ADD_REQUEST'
// DATA TYPES
export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const SET_SELECTED_PROFILE = 'SET_SELECTED_PROFILE'
export const SET_SELECTED_POSTS = 'SET_SELECTED_POSTS'
export const SET_NEW_POST = 'SET_NEW_POST'
export const DELETE_POST = 'DELETE_POST'
export const SET_POST = 'SET_POST'
export const SET_LIKES = 'SET_LIKES'
export const SET_DISLIKE = 'SET_DISLIKE'
export const SET_SUBSCRIPTIONS_POSTS = 'SET_SUBSCRIPTIONS_POSTS'
export const CLEAR_POSTS = 'CLEAR_POSTS'
export const SET_NEW_SUBSCRIPTIONS_POSTS = 'SET_NEW_SUBSCRIPTIONS_POSTS'
// COMMENT TYPES
export const SET_NEW_COMMENT = 'SET_NEW_COMMENT'
export const SET_POST_COMMENTS = 'SET_POST_COMMENTS'
export const SET_REPLIES = 'SET_REPLIES'
export const DELETE_REPLY = 'DELETE_REPLY'
export const DELETE_COMMENT = 'DELETE_COMMENT'
// UI TYPES
export const ON_HOME = 'ON_HOME'
export const ON_EXPLORE = 'ON_EXPLORE'
export const FOCUS_OFF = 'FOCUS_OFF'
export const ON_SINGLE_POST = 'ON_SINGLE_POST'
export const CLOSE_SINGLE_POST = 'CLOSE_SINGLE_POST'
export const CHANGING_PROFILE_IMAGE = 'CHANGING_PROFILE_IMAGE'
export const PROFILE_IMAGE_CHANGED = 'PROFILE_IMAGE_CHANGED'
export const OPEN_MENU = 'OPEN_MENU'
export const CLOSE_MENU = 'CLOSE_MENU'
// NOTIFICATION TYPES
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const SET_NEW_NOTIFICATION = 'SET_NEW_NOTIFICATION'
export const MARK_NOTIFICATIONS_AS_READED = 'MARK_NOTIFICATIONS_AS_READED'
// SOCKET TYPES
export const SET_USER_SOCKET = 'SET_USER_SOCKET'





